<?php

/**
 * @file
 * Contains user_points_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_points_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_points_login module.
    case 'help.page.user_points_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Reward points to users on login') . '</p>';
      return $output;

    default:
  }
}
