user_points_login.settings:
  type: config_object
  label: 'User Points Login Settings'
  mapping:
    login_points:
      type: integer
      label: 'No. of points to be rewarded'
    frequency:
      type: integer
      label: 'No. of hours after which points are rewarded again'
